# Specify Docker Compose file format version
version: '3.8'

# Define the services that make up your application
services:
  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

  # First app instance
  app1:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://jabick10:Baole2004@projectnodejs.7x9uw.mongodb.net/products
      - SESSION_SECRET=secret
      - INSTANCE_ID=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IS_DOCKER=true
    depends_on:
      - redis
    restart: unless-stopped

  # Second app instance
  app2:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://jabick10:Baole2004@projectnodejs.7x9uw.mongodb.net/products
      - SESSION_SECRET=secret
      - INSTANCE_ID=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IS_DOCKER=true
    depends_on:
      - redis
    restart: unless-stopped

  # Third app instance
  app3:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://jabick10:Baole2004@projectnodejs.7x9uw.mongodb.net/products
      - SESSION_SECRET=secret
      - INSTANCE_ID=3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IS_DOCKER=true
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: 